### ISSUE TITLE
rx namespace collision with io.reactivex

### ISSUE THREAD

**Issue by sgireddy** [Azure/azure-documentdb-rxjava#13]
Many rx components within com.microsoft.azure.documentdb.rx are hiding native rx components forcing me to use _root_ in scala, perhaps its better to leave the term rx where it belongs avoiding confusion. It took me hours to realize that rx components are being hidden... I had to explicitly import the components I needed.

    import _root_.rx.{Completable, SingleSubscriber, Subscriber, Observable => JObservable}
    import _root_.rx.functions.{Action0, Action1, FuncN, Functions}
    import _root_.rx.lang.scala.JavaConversions._
    import _root_.rx.lang.scala.Observable

**Comment by moderakh** [comment]
Can you please explain more what you mean by namespace collision?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sgireddy** [comment]
This issue is specific to Scala. The crux of the problem is with the following import statement:

     import com.microsoft.azure.documentdb._

Scala uses relative package naming which means above statement automatically imports the package rx from com.microsoft.azure.documentdb. This means it hides all packages within the real package "rx" from RxJava. You might argue that "isn't it a bad idea to to import everything from documentdb or even documentdb.rx", I would say "Yes, it is" but when we work on POCs we don't know many classes within the relatively new API so for the sake of convenience we import everything then clean up later.

_root_ is the construct that forces to use absolute package naming. So I had to use it this way in order to overcome the problem.

Here are some more details: https://www.scala-lang.org/old/faq/3.html

Given "rx" is the centerpiece of this library, I would recommend renaming com.microsoft.azure.documentdb.rx to something else, saving time for many naive programmers like me.

**Comment by moderakh** [comment]
@sgireddy 
I haven't done much scala programming myself so your comments on your experience when using in Scala is helpful.

Two questions for you:

1) Please see mongo's rx driver classes, e.g, com.mongodb.rx.client.MapReduceObservable
http://mongodb.github.io/mongo-java-driver-rx/1.1/javadoc/com/mongodb/rx/client/MapReduceObservable.html

Does mongo's rx driver have the same problem on Scala?

2) our rx driver is already used in a scala package:
https://github.com/Azure/azure-cosmosdb-spark/blob/master/src/main/scala/com/microsoft/azure/cosmosdb/spark/CosmosDBSpark.scala#L30-L31

Can you follow the pattern used in the above link? do you see any problem with this approach?

Thanks
